[package]
name = "greasy"
version = "0.1.0"
authors = ["r4gus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
byteorder = "1.3.4"
ascii = "1.0.0"
